import { Code } from "@/components/Code";
import {
  Callout,
  DocsPage,
  H2,
  H3,
  InlineCode,
  P,
  Table,
  Td,
  Th,
} from "@/components/DocsPage";

export default async function SelfHostDocs({
  params,
}: {
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;

  return (
    <DocsPage
      slug="self-host"
      lang={lang}
      title="Self-host"
      description="Production deployment: env variables, security posture, scaling notes, backups. The same code runs in dev and prod."
    >
      <section>
        <H2 id="env-vars">Environment variables</H2>
        <P>
          Generated by <InlineCode>pnpm bootstrap</InlineCode> for dev. In
          production, set them in your secret manager and pass to each
          service.
        </P>
        <Table>
          <thead>
            <tr><Th>Variable</Th><Th>Where</Th><Th>Purpose</Th></tr>
          </thead>
          <tbody>
            <tr>
              <Td mono>DATABASE_URL</Td>
              <Td>control-plane</Td>
              <Td>Postgres with pgvector extension. e.g. <InlineCode>postgres://user:pass@host:5432/relay</InlineCode>.</Td>
            </tr>
            <tr>
              <Td mono>RELAY_MASTER_KEY</Td>
              <Td>control-plane</Td>
              <Td>32-byte hex. Encrypts provider credentials. <strong>Don&apos;t rotate without re-encrypting</strong>.</Td>
            </tr>
            <tr>
              <Td mono>RELAY_INTERNAL_SECRET</Td>
              <Td>both</Td>
              <Td>Shared secret for the runtime → control-plane callback. Set on both services. If unset, the callback is unauthenticated (dev only).</Td>
            </tr>
            <tr>
              <Td mono>RUNTIME_URL</Td>
              <Td>control-plane</Td>
              <Td>Where the runtime listens. Default <InlineCode>http://localhost:4100</InlineCode>.</Td>
            </tr>
            <tr>
              <Td mono>CONTROL_PLANE_URL</Td>
              <Td>runtime</Td>
              <Td>Where the control-plane listens. Default <InlineCode>http://localhost:4000</InlineCode>.</Td>
            </tr>
            <tr>
              <Td mono>PORT</Td>
              <Td>control-plane</Td>
              <Td>HTTP port. Default 4000.</Td>
            </tr>
            <tr>
              <Td mono>RELAY_TOOL_RESULT_TIMEOUT_MS</Td>
              <Td>control-plane</Td>
              <Td>Custom tool long-poll timeout. Default 30000.</Td>
            </tr>
          </tbody>
        </Table>
      </section>

      <section>
        <H2 id="postgres">Postgres setup</H2>
        <P>
          You need PostgreSQL 16+ with <InlineCode>pgvector</InlineCode>.
          Managed options that include both:
        </P>
        <ul className="list-disc space-y-1 pl-5 text-ink-300">
          <li>Supabase (pgvector built in)</li>
          <li>Neon (enable the <InlineCode>vector</InlineCode> extension)</li>
          <li>RDS for PostgreSQL with the <InlineCode>vector</InlineCode> extension</li>
          <li>Fly.io Postgres (with manual <InlineCode>create extension vector</InlineCode>)</li>
        </ul>
        <P>
          Apply migrations from a checkout of the repo:
        </P>
        <Code
          lang="bash"
          code={`DATABASE_URL=postgres://… pnpm --filter @relayhq/db migrate`}
        />
      </section>

      <section>
        <H2 id="services">Running the services</H2>
        <P>
          Three processes. Any container orchestrator (Fly, Render, Railway,
          Kubernetes, Docker Swarm, plain systemd) works.
        </P>
        <H3 id="runtime-deploy">Runtime (Go)</H3>
        <Code
          lang="bash"
          code={`# build a static binary\ncd runtime\nCGO_ENABLED=0 go build -o relay-runtime ./cmd/runtime\n\n# run it\nCONTROL_PLANE_URL=https://api.relay.your-domain.com \\\n  RELAY_INTERNAL_SECRET=… \\\n  PORT=4100 \\\n  ./relay-runtime`}
        />
        <H3 id="cp-deploy">Control plane (Node)</H3>
        <Code
          lang="bash"
          code={`pnpm --filter @relayhq/control-plane build\nDATABASE_URL=… \\\n  RELAY_MASTER_KEY=… \\\n  RELAY_INTERNAL_SECRET=… \\\n  RUNTIME_URL=http://runtime.internal:4100 \\\n  PORT=4000 \\\n  node packages/control-plane/dist/server.js`}
        />
        <H3 id="dashboard-deploy">Dashboard (Next.js)</H3>
        <P>
          Deploy as a normal Next app (Vercel, Fly, Render, or just{" "}
          <InlineCode>next start</InlineCode>). Set{" "}
          <InlineCode>RELAY_URL</InlineCode> and{" "}
          <InlineCode>RELAY_API_KEY</InlineCode> on its env.
        </P>
        <Code
          lang="bash"
          code={`pnpm --filter @relayhq/dashboard build\nRELAY_URL=https://api.relay.your-domain.com \\\n  RELAY_API_KEY=relay_live_… \\\n  pnpm --filter @relayhq/dashboard start`}
        />
      </section>

      <section>
        <H2 id="bootstrap">Bootstrapping a tenant in production</H2>
        <P>
          The bootstrap script works the same way against a remote Postgres —
          just point <InlineCode>DATABASE_URL</InlineCode> at it.
        </P>
        <Code
          lang="bash"
          code={`DATABASE_URL=postgres://prod-host… \\\n  RELAY_MASTER_KEY=$RELAY_MASTER_KEY \\\n  ANTHROPIC_API_KEY=sk-ant-… \\\n  OPENAI_API_KEY=sk-… \\\n  pnpm bootstrap`}
        />
        <Callout kind="warn">
          The bootstrap prints the new <InlineCode>RELAY_API_KEY</InlineCode>{" "}
          once. Save it before re-running — the hashed lookup means we
          can&apos;t show it again later.
        </Callout>
      </section>

      <section>
        <H2 id="security">Security posture</H2>
        <ul className="list-disc space-y-2 pl-5 text-ink-300">
          <li>
            <strong>Master key:</strong> derive from your secret manager (AWS
            KMS, GCP Secret Manager, 1Password, …). Never put it in source
            control or container env files.
          </li>
          <li>
            <strong>Internal secret:</strong> required in production. The
            control plane warns at boot when it&apos;s missing.
          </li>
          <li>
            <strong>TLS:</strong> terminate at your load balancer (Fly Proxy,
            ELB, Cloudflare). Nothing in Relay does TLS itself.
          </li>
          <li>
            <strong>Network boundaries:</strong> only the control plane needs
            public ingress. Runtime + Postgres stay private.
          </li>
          <li>
            <strong>Tenant isolation:</strong> every read query filters by{" "}
            <InlineCode>tenant_id</InlineCode>. There&apos;s no
            client-supplied tenant id anywhere in the API.
          </li>
          <li>
            <strong>The runtime never sees a Relay key</strong> and has no DB
            access. A compromised runtime instance leaks one in-flight run,
            not your tenant catalog.
          </li>
        </ul>
      </section>

      <section>
        <H2 id="scaling">Scaling notes</H2>
        <P>
          The runtime is stateless — run as many replicas as you want behind a
          load balancer. The control plane is also horizontally scalable, but
          the pending-tools broker is in-memory: sticky sessions OR pin a
          single instance per <InlineCode>(run_id)</InlineCode> until the run
          completes. (A Redis-backed broker is on the roadmap.)
        </P>
      </section>

      <section>
        <H2 id="backups">Backups</H2>
        <P>
          Standard Postgres backups. <InlineCode>pg_dump</InlineCode> nightly
          plus point-in-time recovery if your hosting offers it. The{" "}
          <InlineCode>run_events</InlineCode> table grows fastest (one row per
          token); rotate/archive on a schedule if needed.
        </P>
      </section>

      <section>
        <H2 id="upgrade">Upgrades</H2>
        <P>
          New migrations are forward-compatible by convention. Standard flow:
        </P>
        <ol className="list-decimal space-y-1 pl-5 text-ink-300">
          <li>Pull new code on every service.</li>
          <li><InlineCode>pnpm --filter @relayhq/db migrate</InlineCode> against prod DB.</li>
          <li>Roll runtime, then control plane, then dashboard.</li>
        </ol>
      </section>
    </DocsPage>
  );
}
